fix(cfn-resources): attribute names are not in camel case (#205)
Fixes issues like `aws-ses/lib/email-identity.ts:427:40 - error TS2551:
Property 'attrDkimDnsTokenValue1' does not exist on type
'CfnEmailIdentity'. Did you mean 'attrDkimDNSTokenValue1'?`

---------

Signed-off-by: github-actions <github-actions@github.com>
Co-authored-by: github-actions <github-actions@github.com>